### ISSUE TITLE
add a script to sort automatically bibtex entries

### ISSUE THREAD

**Issue by dvro** [I2Cvb/imbalanced-bibtex#2]
As the list of references increases, it will be difficult to maintain the order. This script would automatically sort entries and even notify if (for some mistake) there are two repeated entries.

**Comment by glemaitre** [comment]
Great idea, a python script would be great

**Comment by dvro** [comment]
I'd also advise sorting either by `year-author-title` so recent papers could be on top.
Or, `author-year-title`, so papers from the same author would be together.

**Comment by glemaitre** [comment]
yep, I don't have problem with that. At first, it was to have a standard. Since that there is python library to parse the bib file, the resorting should possible without to much problem.

**Comment by chkoar** [comment]
I would prefer that (This is a soft recommendation)

> author-year-title, so papers from the same author would be together

Do we have already this script?

**Comment by glemaitre** [comment]
Nop, we have to write it :D

**Comment by chkoar** [comment]
Great. I could draft it.

> https://github.com/sciunto-org/python-bibtexparser

**Comment by glemaitre** [comment]
Yep this one.

**Comment by chkoar** [comment]
I've implemented that function.
Do we need commandline args or just `python sort_bibtex.py` to sort the `imbalanced-bibtex.bib`?

**Comment by glemaitre** [comment]
For the moment just `python sort_bibtex.py`. We will modify if needed. We could use Travis to trigger the sorting and automatically pushed. It is about the same than with documentation.

**Comment by glemaitre** [comment]
Ok I added a script which automatically trigger the sorting with a push on the master using Travis.

**Comment by chkoar** [comment]
It doesn't seem to work :(

**Comment by glemaitre** [comment]
It is strange https://travis-ci.org/I2Cvb/imbalanced-bibtex/builds/164237918
It seems that after sorting there is nothing to push

**Comment by glemaitre** [comment]
this is solved. I forgot that he was detaching the HEAD from master. So while commiting, I was not in master any more, so nothing to push
